security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
            pattern: ^/admin
            anonymous: ~
            form_login:
                login_path:  anh_admin_login
                check_path:  anh_admin_login_check
            logout:
                path: /admin/logout
                target: /

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
