parameters:
#    anh_site.example.class: Anh\Bundle\SiteBundle\Example

services:
#    anh_site.example:
#        class: %anh_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
