parameters:
    anh_site.date_format: 'Y-m-d H:i:s'

services:
    anh_site.date_format_listener:
        class: Anh\SiteBundle\EventListener\DateFormatListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
